# tkinter_scenario_selector 地址
LOC_TKINTER: tkinter_scenario_selector.py

# Classic_Scenarios_Selection.py 地址
LOC_CLASSIC_SCENARIOS: Classic_Scenarios_Selection.py

# debug地址
LOC_DEBUG: "DEBUG_TSRL"

# Railway Transportation System - Model1 地址
LOC_RAILWAY_MODEL1: Railway Transportation System\Model1\Model1.alp

# Railway Transportation System - Path Conflict1 地址
LOC_RAILWAY_PATH_CONFLICT1: Railway Transportation System\Path Conflict1\Path Conflict1.alp

# Ship Transportation System - Model4 地址
LOC_SHIP_MODEL4: Ship Transportation System\ship Model\Model4.alp

# SUMO GUI地址
SUMO_GUI: sumo-1.15.0\bin\sumo-gui.exe

# SUMO netedit.exe 地址
LOC_SUMO_NETEDIT: sumo-1.15.0\bin\netedit.exe

# SUMO netconvert.exe 地址
LOC_SUMO_NETCONVERT: sumo-1.15.0\bin\netconvert.exe

# SUMO.exe 地址
LOC_SUMO: sumo-1.15.0\bin\sumo.exe

# 手动创建路网说明文件地址
LOC_MANUAL_NETWORK_CREATION: manual_network_creation.html

# 仿真配置文件地址
LOC_CONFIG: trafficManager\config.yaml